<?php
/**
 * The icon library: resolving a slug to SVG.
 *
 * @package Zealblocks
 */

namespace Zealblocks\Icon_Handler;

defined( 'ABSPATH' ) || exit;

/**
 * Reads icon-handler/icons.php and turns a slug into markup.
 *
 * WHAT IS STORED, AND WHAT IS NOT.
 *
 * A block saves only the SLUG — `heart`, never the SVG. Both the front end and
 * the editor resolve that slug back to geometry at render time, which is what
 * keeps post content small, keeps a re-generated icon set applying to existing
 * content, and means a design fix does not require touching the database.
 *
 * WHY THE FILE IS LOADED LAZILY.
 *
 * icon-handler/icons.php calls __() around 2000 times. WordPress raises
 * _doing_it_wrong for a text domain used before `after_setup_theme`
 * (wp-includes/l10n.php:1444), so requiring it at plugin bootstrap would trip
 * that on every request. Loading on first lookup means it happens inside a
 * render callback, which always runs after `init`.
 *
 * It also means a page with no icons never pays for it: reading one icon costs
 * the whole file — ~4 ms and ~3 MB — because there is no partial include.
 */
final class Library {

	/**
	 * The icon set, or null before the first lookup.
	 *
	 * @var array<string, array>|null
	 */
	private static $icons = null;

	/**
	 * Loads the icon set once per request.
	 *
	 * @return array<string, array> Slug => { label, width, height, path }.
	 */
	private static function all() {
		if ( null !== self::$icons ) {
			return self::$icons;
		}

		$file = __DIR__ . '/icons.php';

		/*
		 * icon-handler/ is generated by `npm run update-icons`. A checkout that
		 * has not been generated should render no icons, not fatal.
		 */
		self::$icons = is_readable( $file ) ? require $file : array();

		return self::$icons;
	}

	/**
	 * Every icon, for the one caller that genuinely needs the whole set.
	 *
	 * That caller is the picker's index (Catalog::index()), which labels 1992
	 * grid cells. Everything else resolves by slug and must keep doing so —
	 * handing the full array around is how a front-end path ends up loading
	 * 1.5 MB to draw one glyph.
	 *
	 * @return array<string, array> Slug => { label, width, height, path }.
	 */
	public static function all_icons() {
		return self::all();
	}

	/**
	 * Looks up one icon.
	 *
	 * @param string $slug Icon slug, e.g. 'heart'.
	 * @return array|null { label, width, height, path }, or null if unknown.
	 */
	public static function get( $slug ) {
		if ( ! is_string( $slug ) || '' === $slug ) {
			return null;
		}

		$icons = self::all();

		return $icons[ $slug ] ?? null;
	}

	/**
	 * Looks up several icons at once.
	 *
	 * Used by the REST route, which the editor calls with every slug a post
	 * contains — so one request covers the whole page rather than one per
	 * block.
	 *
	 * @param string[] $slugs Icon slugs.
	 * @return array<string, array> Only the slugs that exist.
	 */
	public static function get_many( array $slugs ) {
		$found = array();

		foreach ( $slugs as $slug ) {
			$icon = self::get( $slug );

			if ( $icon ) {
				$found[ $slug ] = $icon;
			}
		}

		return $found;
	}

	/**
	 * Renders an icon as SVG markup.
	 *
	 * The wrapper is rebuilt here rather than stored, which is why the
	 * generated file keeps only a path: the same geometry can be given
	 * different classes, sizes and labels without regenerating anything.
	 *
	 * @param string $slug  Icon slug.
	 * @param array  $args {
	 *     Optional.
	 *
	 *     @type string $class Additional class names.
	 *     @type string $label Accessible label. When empty the SVG is hidden
	 *                         from assistive technology, which is correct for
	 *                         an icon sitting beside its own text.
	 * }
	 * @return string SVG markup, or '' when the slug is unknown.
	 */
	public static function render( $slug, array $args = array() ) {
		$icon = self::get( $slug );

		if ( ! $icon ) {
			return '';
		}

		$class = isset( $args['class'] ) ? trim( 'zealblocks-icon ' . $args['class'] ) : 'zealblocks-icon';
		$label = $args['label'] ?? '';

		$accessibility = '' !== $label
			? sprintf( ' role="img" aria-label="%s"', esc_attr( $label ) )
			: ' aria-hidden="true" focusable="false"';

		return sprintf(
			'<svg class="%1$s" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 %2$d %3$d" fill="currentColor"%4$s><path d="%5$s"/></svg>',
			esc_attr( $class ),
			(int) $icon['width'],
			(int) $icon['height'],
			$accessibility,
			esc_attr( $icon['path'] )
		);
	}
}
